#!/bin/bash


# 生成公私钥
private_key=~/.ssh/id_rsa
public_key=~/.ssh/id_rsa.pub
if [ ! -s $private_key ] || [ ! -s $public_key ]; then
    umask 077
    test -d ~/.ssh || mkdir ~/.ssh
    ssh-keygen -q -t rsa -f $private_key -N ""
    echo "新的公钥、私钥生成！"
    echo
fi

# 输入域帐号
ask() {
    while true; do
        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        read -ep "$1 [$prompt] " REPLY

        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}
user=$USER
if [ -z "$user" ]; then user=$USERNAME; fi

if [ -n "$user" ]; then
    if ! ask "当前用户名 '$user' 是否是域帐号？" Y; then
        while true; do
            read -p "请输入域帐号：" user
            if [ -n "$user" ]; then break; fi
        done
    fi
else
    while true; do
        read -p "请输入域帐号：" user
        if [ -n "$user" ]; then break; fi
    done
fi
echo

# 配置 .ssh/config
ssh_config=~/.ssh/config
platform=$(uname -s)
setconfig() {
    echo "# generated by qzz-copy-id" >> $ssh_config
    echo "Host 192.168.237.7* 10.86.*.* l-qzz*.fe.dev.cn*.qunar.com" >> $ssh_config
    echo "    User $user" >> $ssh_config
    echo "添加以下配置到 $ssh_config"
    echo -e "    \033[34m# generated by qzz-copy-id\033[0m"
    echo -e "    \033[34mHost 192.168.237.7* 10.86.*.* l-qzz*.fe.dev.cn*.qunar.com\033[0m"
    echo -e "        \033[34mUser $user\033[0m"
    echo
}
if [ "Darwin" = "$platform" ]; then
    if [ -f $ssh_config ]; then
        sed -i "" "/qzz-copy-id/{N;N;N;d;}" $ssh_config
    fi
    setconfig
elif [ "Linux" = "$platform" ]; then
    if [ -f $ssh_config ]; then
        sed -i "/qzz-copy-id/,+3d" $ssh_config
    fi
    setconfig
fi


# 连接跳板机
for_springboard="http://gitlab.corp.qunar.com/fed/qzz-copy-id/raw/v0.0.8/for_springboard.sh"
commands="curl -s -O $for_springboard && bash for_springboard.sh '$(cat $public_key)'"
echo "PASSCODE 是 PIN + TOKEN CODE"
echo "详见 http://wiki.corp.qunar.com/pages/viewpage.action?pageId=16613440"
echo
echo "ssh $user@l-rtools1.ops.cn6.qunar.com"
ssh -o StrictHostKeyChecking=no \
    "$user@l-rtools1.ops.cn6.qunar.com" "$commands"
echo "ssh $user@l-rtools1.ops.cn0.qunar.com"
for i in {39..0}; do
    if [ $i -lt 10 ]; then i="0$i"; fi
    echo -ne "\r请等待 token 更新后再输入 PASSCODE, $i"
    sleep 1
done
echo
ssh -o StrictHostKeyChecking=no \
    "$user@l-rtools1.ops.cn0.qunar.com" "$commands"

